---
title: "Hw5-Analysis"
author: "Hy Mak"
date: "4/26/2018"
output: html_document
---

# Download necessary libaries

```{r setup, message=FALSE}
library(tidyverse)
```

# Import Rule of Law and Democracy Data

```{r}

# Tidy the data

(democracy <- read_csv("uds_summary.csv",
                       col_types = cols(year = col_number())) %>%
    filter(country %in% c("Malaysia", 
                      "Singapore", 
                      "Zambia", 
                      "Ghana", 
                      "Sierra Leone", 
                      "Laos", 
                      "Cambodia", 
                      "Morocco", 
                      "Algeria", 
                      "Tunisia")) %>%
   select(country, year, mean) %>%
   rename(Year = "year",
          Country = "country",
          Demo_Score = "mean"))

(law <- read_csv("Rule_of_law_WB.csv",
                       col_types = cols(Year = col_number())) %>%
    rename(ROL_Estimate = "Rule of Law: Estimate [RL.EST]",
           ROL_Percentile = "Rule of Law: Percentile Rank [RL.PER.RNK]",
           Year = "Time",
           Country = "Country Name") %>%
    select(Year, 
           Country, 
           ROL_Estimate, 
           ROL_Percentile) %>%
    mutate(Country = ifelse(Country == "Lao PDR", 'Laos', Country)) %>%
    mutate(Year = as.numeric(Year)))

(demo_law <- democracy %>%
    left_join(law, by = c("Year", "Country"))
)


```


```{r, message = FALSE}
demo_law %>%
  ggplot(aes(Demo_Score, 
        ROL_Estimate), na.rm = TRUE) +
  geom_point(aes(shape = Country, color = Country)) +
  geom_smooth() +
  scale_y_continuous(limits = c(-1.5, 0.75))+
  scale_x_continuous(limits = c(-1.25, 1))+
  theme_minimal(base_size = 10) +
  labs(x = "Democracy Levels",
       y = "Rule of Law Score",
       title = "Democracy and Rule of Law Relationship")
  
```



```{r}
British <- demo_law %>%
  filter(Country %in% c("Malaysia",
                        "Singapore",
                         "Ghana",
                        "Zambia",
                        "Sierra Leone"))

French <- demo_law %>%
  filter(Country %in% c ("Cambodia",
                         "Laos",
                         "Algeria",
                         "Morocco",
                         "Tunisia"))

ggplot() +
  geom_smooth(data = British, 
              mapping = aes(Demo_Score, ROL_Estimate, 
              color = "Former British Colonies")) +
  geom_smooth(data = French,
              mapping = aes(Demo_Score, ROL_Estimate,
              color = "Former French Colonies"))+
    theme_minimal(base_size = 10) +
    theme(legend.key.size = unit(0.3, "cm"),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal") +
 labs(x = "Democracy Scores",
      y = "Rule of Law Scores",
      title = "Former British & French Colonies",
      subtitle = "Rule of Law and Democracy (1996 - 2016)")


```


```{r}
#Asia & Africa
Asia <- demo_law %>%
  filter(Country %in% c("Malaysia",
                      "Singapore",
                        "Cambodia",
                        "Laos"))
 
Africa <- demo_law %>%
  filter(Country %in% c ("Ghana",
                        "Zambia",
                        "Sierra Leone",
                         "Algeria",
                         "Morocco",
                         "Tunisia"))

ggplot() +
  geom_smooth(data = Asia, 
              mapping = aes(Year, Demo_Score, 
              color = "Asian Countries")) +
  geom_smooth(data = Africa,
              mapping = aes(Year, Demo_Score,
              color = "African Countries"))+
    theme_minimal(base_size = 10) +
    theme(legend.key.size = unit(0.3, "cm"),
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal") +
 labs(x = "Year",
      y = "Democracy Scores",
      title = "Asia and Africa",
      subtitle = "Democratization After Decolonization (1996 - 2016)")
```

```{r}
British %>%
  ggplot(aes(x = Year,
             y = Demo_Score,
             color = Country)) +
  geom_smooth() +
   labs(x = "Year",
      y = "Democracy Scores",
      title = "Democratization",
      subtitle = "Former British Colonies (1996 - 2016)")
  

```




```{r}

demo_law <- demo_law %>%
  mutate(AA = ifelse(Country %in% c("Malaysia","Singapore","Cambodia","Laos"), "Asia", "Africa"))
  
demo_law$Country <- factor(demo_law$Country, levels =c("Malaysia",
            "Singapore",
             "Cambodia",
             "Laos",
              "Ghana",
              "Zambia",
               "Sierra Leone",
                "Algeria",
               "Morocco",
                "Tunisia"))

demo_law %>%
  ggplot(mapping = aes(
    x = Country, 
    y = Demo_Score, 
    fill = AA)) +
  geom_boxplot() +
  theme_minimal(base_size = 10) +
    theme(legend.key.size = unit(0.3, "cm"),
        legend.title = element_blank(),
         axis.text.x = 
            element_text(angle=45, hjust=1)) +
 labs(x = NULL,
      y = "Democracy Scores",
      title = "Asia and Africa",
      subtitle = "Democracy Levels (1956 - 2016)")
  
```

```{r}

British %>%
  ggplot(aes(x = Country,
             y = Demo_Score)) +
  geom_boxplot(aes(color = Country)) +
  theme_minimal(base_size = 10) +
  theme(legend.position="none",
        legend.key.size = unit(0.25, "cm"),
        legend.title = element_blank(),
        axis.text.x = 
            element_text(angle=90, hjust=1)) +
  labs(x = NULL,
       y = "Democracy Scores",
       title = "Democracy Levels (1956 - 2016)")
```
